RF-270: first pass at RMWHub integration
PADAS/gundi-integration-rmwhub pull request #2
Opened 2024-12-04 22:43 UTC by enlivn

## :earth_americas: Summary
RF-270: first pass at RMWHub integration

### :package: Proposed Changes
- Almost everything in this PR was done by @halleyw 
- My only contribution was to update the tests so that they pass locally 2bbfbb56353ec6b6343902c21d2136d9726f56cd

### :tickets: Related tickets

[RF-270](https://allenai.atlassian.net/browse/RF-270)

### :whale2: Manual Testing Steps
1. check out branch
2. `pytest` to run tests locally
3. `docker compose up --build` to spin up a local container to run the code

2024-12-04 22:44 UTC, enlivn commented
@chrisdoehring: Halley is out this week. Would you mind reviewing these changes and see if anything ought to be changed? 🙇🏾‍♂️

2024-12-10 20:59 UTC, chrisdoehring commented on app/actions/helpers.py
> +from gundi_client_v2 import GundiClient
@halleyw it looks like you can remove this file completely.

2024-12-10 21:03 UTC, chrisdoehring commented on app/actions/rmwhub.py
> +    def search_others(self, start_datetime_str: str) -> dict:
It's probably not super critical for this particular integration, but consider making async requests for these classes in the future. You can use `httpx.AsyncClient`. It'll change the logic only a little and will perform better in the serverless environment.

2024-12-10 21:04 UTC, chrisdoehring requested changes
@halleyw I made just a few comments. Have a look and let me know if you'd like to go through them together.

2025-01-12 06:07 UTC, closed without merging

2025-01-12 06:08 UTC, halleyw commented
The implementation for the RmwHub Action Runner has significantly changed due to the addition of the `search_hub` endpoint in their API. This warrants a new PR.